version: '3.7'
services:

  nwserver:
    hostname: nwserver
    build:
      context: ./
    volumes:
    - c:/NeverwinterNights/NWN:/nwn/home
    - ${PWD-.}/logs:/nwn/run/logs.0
    - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
    restart: unless-stopped
    ports:
    - '5121:5121/udp'
    networks:
    - backend

networks:
    backend: